name: af_analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy>=1.21
  - pandas>=1.3.4
  - tqdm>=4.0
  - seaborn>=0.11
  - cmcrameri>=1.7
  - nglview>=3.0
  - ipywidgets>=7.6
  - ipympl>=0.9.8
  - mdanalysis>=2.4
  - scikit-learn
  - pip
  - pip:
      - pdb_cpp>=0.0.1
      - af-analysis @ file:.
